Controllers/OrderTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JazzCPO5.Models;

namespace JazzCPO5.Controllers
{
    public class OrderTablesController : Controller
    {
        private JazzCP05Entities db = new JazzCP05Entities();

        // GET: OrderTables
        public ActionResult Index()
        {
            var orderTables = db.OrderTables.Include(o => o.CustomerTable).Include(o => o.ProductTable);
            //ViewBag.cusName3 = (string)Session["customerName"];

            return View(orderTables.ToList());
        }

 //       public ActionResult Design()    // used to be in home controller
 //       {
            //var orderTables = db.OrderTables.Include(o => o.CustomerTable).Include(o => o.ProductTable);
            //ViewBag.cusName3 = (string)Session["customerName"];

  //          return View("Design");
    //    }



        public ActionResult PlaceOrder()                     // 
        {
            if (Session["customerName"] == null)
            {
                return RedirectToAction("Home", "Home" , new { area = "Admin" });
                //return View("Home/Design");
            }
            else
            {
                string nameCart = ViewBag.cusName = (string)Session["customerName"];
                CustomerTable cus1 = db.CustomerTables.Where(s => s.Name == nameCart).ToList().FirstOrDefault();    //added ToList()
                int x1 = 1;
                //ProductTable prod1 = new ProductTable();
                //OrderTable ord1 = new OrderTable();

                foreach (CartTable car1 in db.CartTables)
                {
                    ProductTable prod1 = new ProductTable();
                    prod1 = db.ProductTables.Where(s => s.Name == car1.Name).ToList().FirstOrDefault();       // FIXED!!!    added ToList()

                    OrderTable ord1 = new OrderTable();
                    ord1.OrderID = (db.OrderTables.Count() + x1);
                    ord1.CustomerID = cus1.CustomerID;
                    ord1.ProductID = prod1.ProductID;                                                // FIXED!!!
                    ord1.Date = DateTime.Today.ToString("d");
                    ord1.Quantity = car1.Quantity;
                    ord1.Total = (car1.Quantity * car1.Price);
                    x1++;

                    db.OrderTables.Add(ord1);
                }

                foreach (CartTable car2 in db.CartTables)                            // Delete items from cart
                {
                    db.CartTables.Remove(car2);
                }

                db.SaveChanges();                                                    // Save changes after loop!
                return RedirectToAction("Index");
            }
        }




        // GET: OrderTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderTable orderTable = db.OrderTables.Find(id);
            if (orderTable == null)
            {
                return HttpNotFound();
            }
            return View(orderTable);
        }

        // GET: OrderTables/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.CustomerTables, "CustomerID", "Name");
            ViewBag.ProductID = new SelectList(db.ProductTables, "ProductID", "Name");
            return View();
        }

        // POST: OrderTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderID,CustomerID,ProductID,Date,Quantity,Total")] OrderTable orderTable)
        {
            if (ModelState.IsValid)
            {
                db.OrderTables.Add(orderTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.CustomerTables, "CustomerID", "Name", orderTable.CustomerID);
            ViewBag.ProductID = new SelectList(db.ProductTables, "ProductID", "Name", orderTable.ProductID);
            return View(orderTable);
        }

        // GET: OrderTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderTable orderTable = db.OrderTables.Find(id);
            if (orderTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.CustomerTables, "CustomerID", "Name", orderTable.CustomerID);
            ViewBag.ProductID = new SelectList(db.ProductTables, "ProductID", "Name", orderTable.ProductID);
            return View(orderTable);
        }

        // POST: OrderTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderID,CustomerID,ProductID,Date,Quantity,Total")] OrderTable orderTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.CustomerTables, "CustomerID", "Name", orderTable.CustomerID);
            ViewBag.ProductID = new SelectList(db.ProductTables, "ProductID", "Name", orderTable.ProductID);
            return View(orderTable);
        }

        // GET: OrderTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderTable orderTable = db.OrderTables.Find(id);
            if (orderTable == null)
            {
                return HttpNotFound();
            }
            return View(orderTable);
        }

        // POST: OrderTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderTable orderTable = db.OrderTables.Find(id);
            db.OrderTables.Remove(orderTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JazzCPO5.Models;

namespace JazzCPO5.Controllers
{
    public class ProductTablesController : Controller
    {
        private JazzCP05Entities db = new JazzCP05Entities();

        // GET: ProductTables
        public ActionResult Index()
        {
            return View(db.ProductTables.ToList());

        }

        public ActionResult IndexProducts()                  //DELETE LATER?
        {
            return View(db.ProductTables.ToList());
        }

        public ActionResult IndexCart()
        {
            decimal x1 = 0M;

            foreach (CartTable item in db.CartTables.ToArray())
            {
                x1 += (item.Quantity * item.Price);
            }
            ViewBag.TotPrice = x1;

            return View(db.CartTables.ToList());
        }

        public ActionResult Index2()                  // Displays the products and cart
        {
            return View(db.ProductTables.ToList());
        }



        public ActionResult SelectCustomer()                  // Select Customer
        {
            ViewBag.customers = db.CustomerTables.Select(i => new SelectListItem() { Text = i.Name });  // delete this soon
            ViewBag.cusName = Session["customerName"] = Request["customers"];

  //          if (ViewBag.cusName != null)
  //          {
  //              CartTable cart6 = db.CartTables.Where(s => s.Name == "Miles Ahead").FirstOrDefault();
  //              cart6.Image = ViewBag.cusName;
  //              Session["customerName"] = cart6.Image;
  //              db.SaveChanges(); 
  //          }

            return View(db.ProductTables.ToList());
        }



        public ActionResult ADD(int? id)                                // ADD to CartTable
        {
            ProductTable product1 = db.ProductTables.Find(id);
            string name1 = db.ProductTables.Find(id).Name;
            CartTable cart1 = db.CartTables.Where(s => s.Name == name1).FirstOrDefault();

            if(cart1 == null)
            {
                CartTable cart2 = new CartTable();
                cart2.CartID = db.ProductTables.Find(id).ProductID;
                cart2.Name = name1;
                cart2.Price = db.ProductTables.Find(id).Price;
                cart2.Image = db.ProductTables.Find(id).Image;
                cart2.Quantity = 1;

                db.CartTables.Add(cart2);
                db.SaveChanges();
            }
            else
            {
                cart1.Quantity++;
                db.SaveChanges();
            }

            return RedirectToAction("Index2");
        }

        public ActionResult RFT(int? id)                                // remove from CART
        {
            CartTable cart4 = db.CartTables.Find(id);
            db.CartTables.Remove(cart4);
            db.SaveChanges();

            return RedirectToAction("Index2");
        }






        // GET: ProductTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTables.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
        }

        // GET: ProductTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,Name,Price,Image")] ProductTable productTable)
        {
            if (ModelState.IsValid)
            {
                db.ProductTables.Add(productTable);
                db.SaveChanges();
                //return RedirectToAction("Index");                   
                return View("~/Views/CustomerTables/index.cshtml", db.CustomerTables.ToList());
                //return View("~/Views/CustomerTables", db.CustomerTables.ToList());
            }

            return View(productTable);
        }

        // GET: ProductTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTables.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
           
        }

        // POST: ProductTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,Name,Price,Image")] ProductTable productTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productTable).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
                //return RedirectToAction("Index", "CustomerTablesController");
                //return RedirectToAction("IndexCus");
                //return View("~/Views/Home/Design.cshtml");
                return View("~/Views/CustomerTables/index.cshtml", db.CustomerTables.ToList());
            }
            return View(productTable);
            //return View("IndexCus");                     //\Views\CustomerTables\Index.cshtml
            //return RedirectToAction("customerTable", "CutomerTablesController");
        }

        // GET: ProductTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductTable productTable = db.ProductTables.Find(id);
            if (productTable == null)
            {
                return HttpNotFound();
            }
            return View(productTable);
        }

        // POST: ProductTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductTable productTable = db.ProductTables.Find(id);
            db.ProductTables.Remove(productTable);
            db.SaveChanges();
            //return RedirectToAction("Index");
            return View("~/Views/CustomerTables/index.cshtml", db.CustomerTables.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/IndexCus.cshtml
@model IEnumerable<JazzCPO5.Models.CustomerTable>

@{
    ViewBag.Title = "IndexCus";
}


@*<link href="StyleSheet1.css" rel="stylesheet" />*@

<div class="row">
    <div class="col-sm-6">

        <h2><span>CUSTOMERS</span></h2>

        <p>
            @Html.ActionLink("Create New", "Create", null, new { @class = "classname" })
        </p>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.CustomerID }, new { @style = "color:white;" }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.CustomerID }) |*@
                        @Html.ActionLink("Delete", "Delete", new { id = item.CustomerID }, new { @style = "color:white;" })
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="col-sm-6">
        <h2><span>Products</span></h2>
        @{Html.RenderAction("IndexProducts");}
    </div>

</div>

Views/Shared/IndexProducts.cshtml
@model IEnumerable<JazzCPO5.Models.ProductTable>

@{
    ViewBag.Title = "IndexProducts";
}

<style>
    img {
        width: 50px;
        height: 50px;
    }
</style>



@*<h2>Index</h2>*@

<p>
    @Html.ActionLink("Create New", "Create", "ProductTables", null, new { @class = "classname" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Image)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.Image)*@
            <img src="@item.Image">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", "ProductTables", new { id=item.ProductID }, new { @style ="color:white;" }) |
            @*@Html.ActionLink("Details", "Details", "ProductTables", new { id=item.ProductID }, null) |*@
            @Html.ActionLink("Delete", "Delete", "ProductTables", new { id=item.ProductID }, new { @style = "color:white;" })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JAZZ CDs</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<style>
    body {
        background-image: url("/Images/milesdavis.png");
        background-size: cover;
    }

    table{
        background-color: black;
        color: white;
        opacity: 0.7;
        text-align: center;
    }

    h2 {
        text-align: center;
        color: white;
    }

    span {
        background-color: black;
        font-weight: bold;
        opacity: 0.8;
    }

    th {
        text-align: center;
    }


    a.classname
    {
        /*background: url(../Images/image.gif) no-repeat top left;*/

        background-color: black;
        border: none;
        color: white;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 20px;
        margin: 4px 2px;
        cursor: pointer;
        opacity: 0.7;

   /*   display: block;
        width: 150px;
        height: 150px;
        text-indent: -9999px;  hides the link text */
    }

    a.classname:hover {                 /* Invert colours of button */
        /*background-color: white; 
        color: black;
        opacity: 0.7;*/

        opacity: 1;
        color: white;
        }

    #btnChange {
        background-color: black;
        color: white;
        opacity: 0.7;
    }

    #btnChange:hover {           
        opacity: 1;
     }




</style>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("HOME", "Home", "Home")</li>
                    <li>@Html.ActionLink("SHOP", "Index2", "ProductTables")</li>
                    <li>@Html.ActionLink("ORDERTABLE", "Index", "OrderTables")</li>
                    <li>@Html.ActionLink("CUSTOMERS/STOCK", "Index", "CustomerTables")</li>
                    <li>@Html.ActionLink("DESIGN", "Design", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>