Controllers/CustomerTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JazzCPO5.Models;

namespace JazzCPO5.Controllers
{
    public class CustomerTablesController : Controller
    {
        private JazzCP05Entities db = new JazzCP05Entities();

        // GET: CustomerTables
        public ActionResult Index()
        {
            return View(db.CustomerTables.ToList());
        }

        public ActionResult IndexProducts()
        {
            return View(db.ProductTables.ToList());
        }

        public ActionResult IndexCus()                              // delete later?
        {
            return View(db.CustomerTables.ToList());
        }

        // GET: CustomerTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerTable customerTable = db.CustomerTables.Find(id);
            if (customerTable == null)
            {
                return HttpNotFound();
            }
            return View(customerTable);
        }

        // GET: CustomerTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,Name,Email")] CustomerTable customerTable)
        {
            if (ModelState.IsValid)
            {
                db.CustomerTables.Add(customerTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customerTable);
        }

        // GET: CustomerTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerTable customerTable = db.CustomerTables.Find(id);
            if (customerTable == null)
            {
                return HttpNotFound();
            }
            return View(customerTable);
        }

        // POST: CustomerTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,Name,Email")] CustomerTable customerTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customerTable);
        }

        // GET: CustomerTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerTable customerTable = db.CustomerTables.Find(id);
            if (customerTable == null)
            {
                return HttpNotFound();
            }
            return View(customerTable);
        }

        // POST: CustomerTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerTable customerTable = db.CustomerTables.Find(id);
            db.CustomerTables.Remove(customerTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CustomerTables/Create.cshtml
@model JazzCPO5.Models.CustomerTable

@{
    ViewBag.Title = "Create";
}

<h2><span>Create</span></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="btnChange" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CustomerTables/Delete.cshtml
@model JazzCPO5.Models.CustomerTable

@{
    ViewBag.Title = "Delete";
}

<h2><span>Delete</span></h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" id="btnChange" /> 
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

Views/CustomerTables/Details.cshtml
@model JazzCPO5.Models.CustomerTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CustomerTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/CustomerTables/Edit.cshtml
@model JazzCPO5.Models.CustomerTable

@{
    ViewBag.Title = "Edit";
}

<h2><span>Edit</span></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="btnChange"/>
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CustomerTables/Index.cshtml
@model IEnumerable<JazzCPO5.Models.CustomerTable>

@{
    ViewBag.Title = "Index";
}


@*<link href="StyleSheet1.css" rel="stylesheet" />*@

<div class="row">
    <div class="col-sm-6">

        <h2><span>CUSTOMERS</span></h2>

        <p> 
            @*@Html.ActionLink("Create New", "Create", null, new { @class = "classname" })*@  
            @Html.ActionLink("Create New", "Create", "CustomerTables", null, new { @class = "classname" })
        </p>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "CustomerTables", new { id = item.CustomerID }, new { @style = "color:white;" }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.CustomerID }) |*@
                        @Html.ActionLink("Delete", "Delete", "CustomerTables", new { id = item.CustomerID }, new { @style = "color:white;" })
                    </td>
                </tr>
            }

        </table>

    </div>
    <div class="col-sm-6">
        <h2><span>PRODUCTS</span></h2>
        @{Html.RenderAction("IndexProducts");}
    </div>

</div>